#!/usr/bin/perl
#
# This script sets up a FIFO of all messages collected by syslog.  To make
# syslog write all its logs to the FIFO /etc/syslog.conf is modified.
#
# In OpenBSD the script adds a new table to /etc/pf.conf
#    table <crackers> { }
#
# In Linux no other steps are done.
#
# Next the config file is installed as /etc/logrun.conf and then modified
# according to the local firewall setup.
#
# On OpenBSD pfctl is setup:
#    $ipv4_firewall = "/sbin/pfctl -t crackers -T add ";
#    $ipv6_firewall = $ipv4_firewall;
#
# On Linux shorewall, iptables or ipchains is setup, e.g.:
#    $ipv4_firewall = /sbin/shorewall drop ";
#    $ipv6_firewall = $ipv4_firewall;
#
#
$| = 1;

$system=`uname`;

if($system =~ /Linux/) {
  $YOURSYSTEM = 1;
  print "\nYour system: $system\n";
} elsif ($system =~ /OpenBSD/) {
  $YOURSYSTEM = 2;
  print "\nYour system: $system\n";
} else {
  print "This setup file can't install logrun on Your $system system !!!\n";
  print "Read INSTALL file and do it manually!\n\n";
  exit(1);
}

print "I'm creating /dev/logrun FIFO file: ";
system("mkfifo /dev/logrun") == 0 or print "Can't create /dev/logrun FIFO file: $!\nYou should be root now!!!\n";
system("chmod 600 /dev/logrun") == 0 or print "Can't change /dev/logrun mode for 600: $!\n\n";
print "OK\n";

print "I'm changing Your syslog: ";
if(open(SYSLOG, ">>/etc/syslog.conf") != 0) {
  print SYSLOG "\nauth,authpriv.*\t\t\t|/dev/logrun";
  close(SYSLOG);
  print "OK\n";
  print "I'm reloading Your syslogd: ";
  system("ps ax|grep syslog|grep -v grep|awk \'\{system\(\"kill -1 \"\$1\)\}\'");
  print "OK\n";
} else {
  print "FAILED!!! - change Your syslog.conf file manually and add there line:\n\tauth,authpriv.*\t\t\t|/dev/logrun\n";
}

if($YOURSYSTEM eq "2") {
  #BSD
  print "I'm changing Your /etc/pf.conf: ";
  if(open(PFCONF, ">>/etc/pf.conf") != 0) {
    print PFCONF "\ntable <crackers> \{ \}\n";
    close(PFCONF);
    print "OK\n";
    print "I'm reloading Your PF ( Ctrl+C to stop ) - pfctl -f /etc/pf.conf:";
    sleep(2);
    print ".";
    sleep(2);
    print ".";
    sleep(2);
    print ".";
    sleep(2);
    if(system("/sbin/pfctl -f /etc/pf.conf") == 0) {
      print "OK\n";
    } else {
      print "FAILED!!! - Can't reload Your PF filter\n";
    }
  } else {
    print "FAILED!!! - change Your pf.conf file manually and add there line:\n\ttable\<crackers\> \{ \}\n";
  }
}


system("chown root ./logrun") == 0 or print "Can't change ./logrun owner for root: $!\n\n";
system("chmod 700 ./logrun") == 0 or print "Can't change ./logrun mode for 700: $!\n\n";
system("cp -f ./logrun /usr/sbin/logrun");

print "I'm creating /var/log/logrun file: ";
system("touch /var/log/logrun") == 0 or print "Can't touch /var/log/logrun: $!\n\n";
system("chmod 600 /var/log/logrun") == 0 or print "Can't change /var/log/logrun mode for 600: $!\n\n";
system("chown root /var/log/logrun") == 0 or print "Can't change /var/log/logrun owner for root: $!\n\n";
print "OK\n";


if($YOURSYSTEM eq "2") {
  #BSD
  print "I'm creating /etc/logrun.conf file: ";
  if(open(LOGCONF, ">/etc/logrun.conf") != 0) {
    print LOGCONF <<EOT;
#file where syslogd logs data for logrun
\$logfile="/dev/logrun";

#failed logins database
\$failfile="/var/log/logrun";

#how many times ONE host can try to fail login
\$failedattempts=4;

#don't add these IP numbers into database - You MUST to add netmask after IP
\@dont_add_into_database = ( "127.0.0.0/255.0.0.0", "192.168.0.0/255.255.255.0");

#at the end of this value func update_iptables adds IP
\$command_iptables="/sbin/pfctl -t crackers -T add ";

#facility for syslog (man syslog.conf)
\$facility="daemon";

#PID file location
\$pidfile="/var/run/logrun.pid";
EOT

  } else {
    print "FAILED!!! - copy logrun.conf to /etc/logrun.conf and edit it\n";
  }

  print "I'm changing Your startup scripts: ";
  if(open(RCS, ">>/etc/rc.local") != 0) {
    print RCS "\n/usr/sbin/logrun\n";
    print RCS "/usr/bin/awk \'\{if \(\$2 >= 4\) system\(\"/sbin/pfctl -t crackers -T add \" \$1\)\}\' /var/log/logrun";
    close(RCS);
    print "OK\n";
  } else {
    print "FAILED!!! - change Your startup scripts and add there lines:\n";
    print "\t/usr/sbin/logrun\n";
    print "\t/usr/bin/awk \'\{if \(\$2 >= 4\) system\(\"/sbin/pfctl -t crackers -T add \" \$1\)\}\' /var/log/logrun";
  }
  print "I'm copying man file: ";
  system("cp -f ./logrun.8 /usr/local/man/man8/logrun.8");
  system("chmod 644 /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 mode for 644: $!\n\n";
  system("chown root /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 owner for root: $!\n\n";
  system("chgrp root /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 group for root: $!\n\n";
  print "OK\n";
} else {
  #Linux
  print "I'm creating /etc/logrun.conf file: ";
  if(open(LOGCONF, ">/etc/logrun.conf") != 0) {
    print LOGCONF <<EOT;
#file where syslogd logs data for logrun
\$logfile="/dev/logrun";

#failed logins database
\$failfile="/var/log/logrun";

#how many times ONE host can try to fail login
\$failedattempts=4;

#don't add these IP numbers into database - You MUST to add netmask after IP
\@dont_add_into_database = ( "127.0.0.0/255.0.0.0", "192.168.0.0/255.255.255.0");

#at the end of this value func update_iptables adds IP
\$command_iptables="/sbin/iptables -I INPUT -j DROP -s ";
\$command_ip6tables="/sbin/ip6tables -I INPUT -j DROP -s ";

#facility for syslog (man syslog.conf)
\$facility="daemon";

#PID file location
\$pidfile="/var/run/logrun.pid";
EOT

  } else {
    print "FAILED!!! - copy logrun.conf to /etc/logrun.conf and edit it\n";
  }

  print "I'm changing Your startup scripts: ";
  if(open(RCS, ">>/etc/init.d/rcS") != 0) {
    print RCS "\n/usr/sbin/logrun\n";
    print RCS "/usr/bin/awk \'\{if \(\$2 >= 4\) system\(\"/sbin/iptables -I INPUT -j DROP -s \" \$1\)\}\' /var/log/logrun";
    close(RCS);
    print "OK\n";
  } else {
    print "FAILED!!! - change Your startup scripts and add there lines:\n";
    print "\t/usr/sbin/logrun\n";
    print "\t/usr/bin/awk \'\{if \(\$2 >= 4\) system\(\"/sbin/iptables -I INPUT -j DROP -s \" \$1\)\}\' /var/log/logrun";
  }
  print "I'm copying man file: ";
  system("cp -f ./logrun.8 /usr/share/man/man8/logrun.8");
  system("chmod 644 /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 mode for 644: $!\n\n";
  system("chown root /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 owner for root: $!\n\n";
  system("chgrp root /usr/share/man/man8/logrun.8") == 0 or print "Can't change /usr/share/man/man8/logrun.8 group for root: $!\n\n";
  print "OK\n";
}

print "Starting /usr/sbin/logrun:";
sleep(1);
print ".";
sleep(1);
print ".";
sleep(1);
print ".\n";
if(system("/usr/sbin/logrun") == 0) {
  system("ps ax|grep /usr/sbin/logrun|grep -v grep") == 0 or die "Can't get PID of process: $!\n\n";
  print "\nEverything is OK.\n";
} else {
 print "Can't run /usr/sbin/logrun: $!\n\nRead INSTALL file and install logrun manually.\n\n";
}
