.\"                                      Hey, EMACS: -*- nroff -*-
.\" Please adjust this date whenever revising the manpage.
.Dd Mar 12, 2017
.Dt LOGRUN 8
.Os
.Sh NAME
.Nm logrun
.Nd scans logfiles for naughty activity and takes proper actions
.Sh SYNOPSIS
.Nm logrun
.Sh DESCRIPTION
This manual page briefly documents the
.Nm
daemon.
.Pp
.Nm
is a UNIX daemon that monitors the system log and scans for suspicious
activity.  It can for instance instruct the system firewall to drop
connections from continuous failed login attempts.  Any action, to any
pattern, is possible to execute.
.Pp
By default
.Nm
instructs netfilter to drop the client IP after ten (10) failed SSH
connections.  All dropped client IP addresses are logged to the log
file.
.Pp
.Nm
may be configured using the
.Pa /etc/logrun.conf
file.
.Sh FILES
.Bl -tag -width /var/lib/logrun/FIFO -compact
.It Pa /etc/logrun.conf
.It Pa /var/log/logrun
.It Pa /var/lib/logrun/FIFO
.El
.Sh AUTHORS
The origin of
.Nm
is the authfail program, by Bartosz M. Krajnik
.Aq bartek@bmk.bz .
Joachim Nilsson and Johan Risberg created logrun, with the idea that any
event, not only authentication failures, can be worth monitoring.
